security:
    encoders:
      FOS\UserBundle\Model\UserInterface:
          algorithm: bcrypt

    providers:
      fos_userbundle:
          id: fos_user.user_provider.username_email

    firewalls:
      dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false

      login:
          pattern:  ^/api/login
          provider: fos_userbundle
          stateless: true
          anonymous: true
          form_login:
              check_path: /api/login_check
              provider: fos_userbundle
              require_previous_session: false
              username_parameter: username
              password_parameter: password
              success_handler:          lexik_jwt_authentication.handler.authentication_success
              failure_handler:          lexik_jwt_authentication.handler.authentication_failure

      api:
          pattern:   ^/api
          stateless: true
          provider: fos_userbundle
          guard:
             authenticators:
              - lexik_jwt_authentication.jwt_token_authenticator
          lexik_jwt:
            authorization_header:
              enabled: true
              prefix:  Bearer
            query_parameter:
              enabled: true
              name:    bearer
            throw_exceptions:        false
            create_entry_point:      true


    access_control:
      - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
      - { path: ^/admin, roles: ROLE_ADMIN }
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }